CREATE OR REPLACE TRIGGER TRG_CUSTOMER
BEFORE INSERT OR UPDATE ON CUSTOMER
FOR EACH ROW
DECLARE 
BEGIN
    IF(:NEW.CREDITS < 0) THEN
    RAISE_APPLICATION_ERROR (-20999, ' The value for CREDIT ' || :NEW.CREDITS || ' has to be above 0! ');
    END IF;
    IF (:NEW.BIRTHDATE >= SYSDATE) THEN
    RAISE_APPLICATION_ERROR (-20998, ' Wrong birthdate! ');
    END IF;
    
    IF (UPDATING)  THEN
    :NEW.BIRTHDATE := :OLD.BIRTHDATE;
    END IF;
    
    IF (NOT REGEXP_LIKE (:NEW.EMAIL, '^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')) THEN
    RAISE_APPLICATION_ERROR (-20997, 'Mail must contain @ sign!');
    END IF;
END TRG_CUSTOMER;
